spring.application.name=api-gateway

server.port=8080

# RUTAS DEL API GATEWAY

spring.cloud.gateway.server.webmvc.routes[0].id=cliente-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/clientes/**

spring.cloud.gateway.server.webmvc.routes[1].id=barbero-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/barberos/**

spring.cloud.gateway.server.webmvc.routes[2].id=reserva-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/reservas/**

spring.cloud.gateway.server.webmvc.routes[3].id=servicio-service
spring.cloud.gateway.server.webmvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/servicios/**

spring.cloud.gateway.server.webmvc.routes[4].id=horario-service
spring.cloud.gateway.server.webmvc.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/horarios/**

spring.cloud.gateway.server.webmvc.routes[5].id=pago-service
spring.cloud.gateway.server.webmvc.routes[5].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/pagos/**

spring.cloud.gateway.server.webmvc.routes[6].id=reporte-service
spring.cloud.gateway.server.webmvc.routes[6].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/reportes/**

spring.cloud.gateway.server.webmvc.routes[7].id=notificacion-service
spring.cloud.gateway.server.webmvc.routes[7].uri=http://localhost:8088
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/notificaciones/**

spring.cloud.gateway.server.webmvc.routes[8].id=sucursal-service
spring.cloud.gateway.server.webmvc.routes[8].uri=http://localhost:8089
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/sucursales/**

spring.cloud.gateway.server.webmvc.routes[9].id=auth-service
spring.cloud.gateway.server.webmvc.routes[9].uri=http://localhost:8090
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/auth/**

spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*